In [ ]:
from pathlib import Path

In [1]:
import pandas as pd
pd.read_parquet("data/alljoined-1.6m/preprocessed-eeg/sub-01/experiment_metadata.parquet")

,image_path,dataset,subject,session,block_id,sequence_id,sequence_image_id,partition,category_name,category_num,category_img_num,dropped
0,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,1,stim_test,jukebox,101,0,False
1,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,2,stim_test,wallpaper,193,0,False
2,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,3,stim_test,ice_cube,97,0,False
3,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,4,stim_test,pug,143,0,False
4,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,5,stim_test,bonnet,18,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
83515,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,4,19,56,16,stim_train,machine_gun,844,8,False
83516,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,4,19,56,17,stim_train,sloth,1303,2,False
83517,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,4,19,56,18,stim_train,hyena,718,6,True
83518,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,4,19,56,19,stim_train,compass,343,0,True
83519,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,4,19,56,20,stim_train,vacuum,1559,8,True

In [ ]:
import pandas as pd
from pathlib import Path

alljoined_path = Path("data/alljoined-1.6m") 

all_metadatas = pd.concat([
    pd.read_parquet(alljoined_path / "preprocessed-eeg" / f"sub-{s:02}" / "experiment_metadata.parquet") for s in range(1, 3)
])

all_metadatas

,image_path,dataset,subject,session,block_id,sequence_id,sequence_image_id,partition,category_name,category_num,category_img_num,dropped
0,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,1,stim_test,jukebox,101,0,False
1,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,2,stim_test,wallpaper,193,0,False
2,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,3,stim_test,ice_cube,97,0,False
3,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,4,stim_test,pug,143,0,False
4,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,1,1,1,1,5,stim_test,bonnet,18,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
83515,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,2,4,19,56,16,stim_train,trunk,1534,4,False
83516,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,2,4,19,56,17,stim_train,tree_trunk,1521,5,False
83517,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,2,4,19,56,18,stim_train,rifle,1161,1,False
83518,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,2,4,19,56,19,stim_train,lion,823,3,False
83519,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,2,4,19,56,20,stim_train,tamale,1439,2,False

In [18]:
all_metadatas = all_metadatas[~all_metadatas["dropped"]].drop(columns=["dropped", "dataset"])
all_metadatas

,image_path,subject,session,block_id,sequence_id,sequence_image_id,partition,category_name,category_num,category_img_num
0,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,1,stim_test,jukebox,101,0
1,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,2,stim_test,wallpaper,193,0
2,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,3,stim_test,ice_cube,97,0
3,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,4,stim_test,pug,143,0
4,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,5,stim_test,bonnet,18,0
...,...,...,...,...,...,...,...,...,...,...
83515,/srv/eeg_reconstruction/shared/data/stimuli/re...,2,4,19,56,16,stim_train,trunk,1534,4
83516,/srv/eeg_reconstruction/shared/data/stimuli/re...,2,4,19,56,17,stim_train,tree_trunk,1521,5
83517,/srv/eeg_reconstruction/shared/data/stimuli/re...,2,4,19,56,18,stim_train,rifle,1161,1
83518,/srv/eeg_reconstruction/shared/data/stimuli/re...,2,4,19,56,19,stim_train,lion,823,3
83519,/srv/eeg_reconstruction/shared/data/stimuli/re...,2,4,19,56,20,stim_train,tamale,1439,2

In [24]:
def _get_all_image_paths(alljoined_path: Path) -> list[Path]:
    return list((alljoined_path / "stimuli" / "images").glob("*.jpg"))

all_paths =  _get_all_image_paths(alljoined_path)

In [ ]:

alljoined_path = Path("data/alljoined-1.6m")
m = load_metadatas(alljoined_path / "preprocessed-eeg", alljoined_path / "imgs", [4, 5])
query_metadata(m, 4, "train")

,image_path,subject,session,block_id,sequence_id,sequence_image_id,partition,category_name,category_num,category_img_num
4080,data/alljoined-1.6m/imgs/07761.jpg,4,1,5,1,1,train,knitting,776,1
5200,data/alljoined-1.6m/imgs/09475.jpg,4,1,6,1,1,train,oar,947,5
6320,data/alljoined-1.6m/imgs/13554.jpg,4,1,7,1,1,train,squash,1355,4
7440,data/alljoined-1.6m/imgs/12662.jpg,4,1,8,1,1,train,shortbread,1266,2
8560,data/alljoined-1.6m/imgs/03804.jpg,4,1,9,1,1,train,crate,380,4
...,...,...,...,...,...,...,...,...,...,...
79039,data/alljoined-1.6m/imgs/08558.jpg,4,4,15,56,20,train,mango,855,8
80159,data/alljoined-1.6m/imgs/15105.jpg,4,4,16,56,20,train,trailer,1510,5
81279,data/alljoined-1.6m/imgs/05490.jpg,4,4,17,56,20,train,fondue,549,0
82399,data/alljoined-1.6m/imgs/01953.jpg,4,4,18,56,20,train,bunkbed,195,3
83519,data/alljoined-1.6m/imgs/15807.jpg,4,4,19,56,20,train,walker1,1580,7

In [11]:
import numpy as np

eeg_obj = np.load(alljoined_path / "preprocessed_eeg" / "sub-08" / "preprocessed_eeg_training_flat.npy", allow_pickle=True)
eeg_obj.keys()

dict_keys(['preprocessed_eeg_data', 'ch_names', 'times'])

In [12]:
eeg_obj["preprocessed_eeg_data"].shape

(66804, 32, 250)