In [5]:
from pathlib import Path
import huggingface_hub

In [4]:
from pathlib import Path
import huggingface_hub

data_path = Path("data")
alljoined_path = data_path / "alljoined-1_6m"

huggingface_hub.snapshot_download("Alljoined/Alljoined-1.6M", allow_patterns="preprocessed_eeg/*", repo_type="dataset", local_dir=alljoined_path)
huggingface_hub.snapshot_download("Alljoined/Alljoined-1.6M", allow_patterns="stimuli.zip", repo_type="dataset", local_dir=alljoined_path)

Fetching 61 files:   0%|          | 0/61 [00:00<?, ?it/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

stimuli.zip:   0%|          | 0.00/661M [00:00<?, ?B/s]

'/home/gasparyanartur/dev/brain-image-implementation/data/alljoined-1_6m'

In [3]:
from pathlib import Path
data_path = Path("data")
alljoined_path = data_path / "alljoined-1_6m"

In [6]:
import zipfile
with zipfile.ZipFile(alljoined_path / "stimuli.zip") as f:
    f.extractall(alljoined_path / "stimuli")

In [48]:
import pandas as pd

all_metadatas = []

for s in range(1, 21):
    all_metadatas.append(pd.read_parquet(alljoined_path / "preprocessed_eeg" / f"sub-{s:02}" / "experiment_metadata_categories.parquet"))

all_metadatas = pd.concat(all_metadatas)
all_metadatas = all_metadatas[~all_metadatas["dropped"]].drop(columns=["dropped", "dataset"])
all_metadatas

,image_path,subject,session,block_id,sequence_id,sequence_image_id,partition,category_name,category_num,category_img_num,super_category,super_category_id,collected
0,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,1,stim_test,jukebox,101,0,household_items_and_furniture,4,NaN
1,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,2,stim_test,wallpaper,193,0,household_items_and_furniture,4,NaN
2,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,3,stim_test,ice_cube,97,0,foods_and_plants,3,NaN
3,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,4,stim_test,pug,143,0,animals,1,NaN
4,/srv/eeg_reconstruction/shared/data/stimuli/re...,1,1,1,1,5,stim_test,bonnet,18,0,body_parts_and_apparel,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
83515,/srv/eeg_reconstruction/shared/data/stimuli/re...,20,4,19,56,16,stim_train,leggings,804,1,body_parts_and_apparel,2,NaN
83516,/srv/eeg_reconstruction/shared/data/stimuli/re...,20,4,19,56,17,stim_train,camper,220,4,vehicles,7,NaN
83517,/srv/eeg_reconstruction/shared/data/stimuli/re...,20,4,19,56,18,stim_train,glue,598,7,tools,5,NaN
83518,/srv/eeg_reconstruction/shared/data/stimuli/re...,20,4,19,56,19,stim_train,sewing_kit,1243,5,tools,5,NaN
83519,/srv/eeg_reconstruction/shared/data/stimuli/re...,20,4,19,56,20,stim_train,latch,793,3,tools,5,NaN

In [47]:
all_metadatas["dataset"].unique()

array(['repr_eeg2'], dtype=object)

In [2]:
all_paths = list((alljoined_path / "stimuli" / "images").glob("*.jpg"))
all_paths

[PosixPath('data/alljoined-1_6m/stimuli/images/04933.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14455.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07067.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09986.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09444.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15548.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12569.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16070.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08514.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02822.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05896.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12598.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01684.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09482.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07958.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05196.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04581.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16211.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13261.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04358.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01284.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04880.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02760.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09213.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00796.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02653.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14068.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10244.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00289.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08276.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15789.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13128.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04764.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07491.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16240.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11073.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05380.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13356.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01742.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09078.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04335.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00535.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03303.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15368.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07656.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13919.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13794.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06898.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05882.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08226.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05391.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13272.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09465.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09921.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02073.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12280.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16378.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15459.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15176.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02249.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03634.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01807.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03828.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04264.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16357.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04561.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04727.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06543.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02378.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16356.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08969.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06742.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15386.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09413.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14907.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09466.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02920.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05365.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15573.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09125.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07010.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11222.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14520.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06299.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01253.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00545.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13587.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14762.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05301.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04645.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15139.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11448.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06413.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13508.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14443.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01480.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08724.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13625.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14286.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06732.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14980.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06026.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12414.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01525.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15093.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03394.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01546.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09305.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11785.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15101.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05782.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12599.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11274.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06911.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12313.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10883.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01151.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04800.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10970.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08647.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01683.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10987.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00895.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09553.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04579.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03466.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12601.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03641.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15185.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05830.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03234.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01724.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11902.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01825.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08880.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08912.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06690.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12610.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05032.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08154.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06175.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15216.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09929.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08888.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15493.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12223.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06349.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16529.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06489.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12932.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00561.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10689.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11098.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12874.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02758.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16089.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01342.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14942.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09492.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10552.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14816.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08362.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03705.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01279.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02347.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07138.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09681.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09725.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11269.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04787.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05166.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13370.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13221.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05983.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04712.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03371.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06514.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12983.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16217.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15863.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09851.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05812.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01925.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09596.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03112.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10598.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02982.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03167.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11711.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04022.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06189.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00646.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08790.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03286.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09831.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11621.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14780.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04301.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07664.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11964.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09442.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14264.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11817.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00126.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11559.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00809.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12636.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02767.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16645.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06006.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00815.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02101.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11901.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12845.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13865.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05134.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10539.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06857.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10736.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15300.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04280.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04582.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12968.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05629.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07288.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12546.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12238.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10016.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03711.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11957.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08966.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16671.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01096.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09897.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05822.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00952.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14320.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03988.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14880.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05125.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02836.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04703.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07802.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08050.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01107.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00045.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14013.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07840.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00963.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12736.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03800.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10718.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07717.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12470.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11966.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11565.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14933.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16663.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12225.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10942.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10675.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07040.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10159.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11206.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11032.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12405.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16385.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01397.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05927.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05138.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13769.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05557.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08905.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03390.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12142.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15034.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13409.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00296.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09936.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10978.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14162.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05873.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05565.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12777.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08202.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14698.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00664.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04533.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06194.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11905.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04473.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15856.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06328.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01346.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06066.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12479.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02477.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07455.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07476.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15931.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00090.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02229.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01666.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15851.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01471.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04400.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15647.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07746.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15423.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02526.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15583.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00111.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11932.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12229.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03272.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13435.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07896.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06204.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12670.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09357.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09739.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00401.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09805.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08461.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08979.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11069.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16301.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03676.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09517.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05741.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12128.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00415.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09583.jpg'),

In [9]:
all_paths

[PosixPath('data/alljoined-1_6m/stimuli/images/04933.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14455.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07067.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09986.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09444.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15548.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12569.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16070.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08514.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02822.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05896.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12598.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01684.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09482.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07958.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05196.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04581.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16211.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13261.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04358.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01284.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04880.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02760.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09213.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00796.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02653.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14068.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10244.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00289.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08276.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15789.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13128.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04764.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07491.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16240.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11073.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05380.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13356.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01742.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09078.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04335.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00535.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03303.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15368.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07656.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13919.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13794.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06898.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05882.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08226.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05391.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13272.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09465.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09921.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02073.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12280.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16378.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15459.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15176.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02249.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03634.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01807.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03828.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04264.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16357.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04561.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04727.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06543.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02378.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16356.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08969.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06742.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15386.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09413.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14907.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09466.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02920.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05365.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15573.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09125.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07010.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11222.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14520.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06299.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01253.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00545.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13587.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14762.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05301.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04645.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15139.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11448.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06413.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13508.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14443.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01480.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08724.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13625.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14286.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06732.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14980.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06026.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12414.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01525.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15093.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03394.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01546.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09305.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11785.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15101.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05782.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12599.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11274.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06911.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12313.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10883.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01151.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04800.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10970.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08647.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01683.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10987.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00895.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09553.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04579.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03466.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12601.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03641.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15185.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05830.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03234.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01724.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11902.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01825.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08880.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08912.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06690.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12610.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05032.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08154.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06175.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15216.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09929.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08888.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15493.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12223.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06349.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16529.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06489.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12932.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00561.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10689.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11098.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12874.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02758.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16089.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01342.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14942.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09492.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10552.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14816.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08362.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03705.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01279.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02347.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07138.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09681.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09725.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11269.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04787.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05166.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13370.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13221.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05983.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04712.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03371.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06514.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12983.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16217.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15863.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09851.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05812.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01925.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09596.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03112.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10598.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02982.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03167.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11711.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04022.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06189.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00646.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08790.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03286.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09831.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11621.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14780.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04301.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07664.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11964.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09442.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14264.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11817.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00126.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11559.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00809.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12636.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02767.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16645.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06006.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00815.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02101.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11901.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12845.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13865.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05134.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10539.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06857.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10736.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15300.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04280.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04582.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12968.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05629.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07288.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12546.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12238.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10016.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03711.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11957.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08966.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16671.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01096.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09897.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05822.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00952.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14320.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03988.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14880.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05125.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02836.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04703.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07802.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08050.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01107.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00045.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14013.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07840.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00963.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12736.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03800.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10718.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07717.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12470.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11966.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11565.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14933.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16663.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12225.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10942.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10675.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07040.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10159.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11206.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11032.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12405.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16385.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01397.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05927.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05138.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13769.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05557.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08905.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03390.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12142.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15034.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13409.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00296.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09936.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/10978.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14162.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05873.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05565.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12777.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08202.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/14698.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00664.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04533.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06194.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11905.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04473.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15856.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06328.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01346.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06066.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12479.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02477.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07455.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07476.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15931.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00090.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02229.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01666.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15851.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/01471.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/04400.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15647.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07746.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15423.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/02526.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/15583.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00111.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11932.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12229.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03272.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/13435.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/07896.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/06204.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12670.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09357.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09739.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00401.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09805.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08461.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/08979.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/11069.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/16301.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/03676.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09517.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/05741.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/12128.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/00415.jpg'),
 PosixPath('data/alljoined-1_6m/stimuli/images/09583.jpg'),

In [10]:
from functools import lru_cache
import re

@lru_cache
def extract_image_id(image_path: str, re_pattern = re.compile(r".+\/(\d+)\.jpg")):
    m = re_pattern.match(image_path)
    assert m is not None
    return m.groups()[0]

p = all_metadatas[3]["image_path"][3]
p, extract_image_id(p)

('/srv/eeg_reconstruction/shared/data/stimuli/repr_eeg2/images/16707.jpg',
 '16707')

In [11]:
import numpy as np

eeg_obj = np.load(alljoined_path / "preprocessed_eeg" / "sub-08" / "preprocessed_eeg_training_flat.npy", allow_pickle=True)
eeg_obj.keys()

dict_keys(['preprocessed_eeg_data', 'ch_names', 'times'])

In [12]:
eeg_obj["preprocessed_eeg_data"].shape

(66804, 32, 250)

In [13]:
all_metadatas[7].query("subject==8").query("partition=='stim_train' & dropped==False").sort_values(["sequence_id", "sequence_image_id"])

,image_path,dataset,subject,session,block_id,sequence_id,sequence_image_id,partition,category_name,category_num,category_img_num,dropped,collected,super_category,super_category_id
4080,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,1,5,1,1,stim_train,jump_rope,756,1,False,True,toys_and_games,6
5200,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,1,6,1,1,stim_train,file2,509,2,False,True,household_items_and_furniture,4
6320,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,1,7,1,1,stim_train,banana_split,60,7,False,True,foods_and_plants,3
7440,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,1,8,1,1,stim_train,diskette,429,1,False,True,household_items_and_furniture,4
8560,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,1,9,1,1,stim_train,bank,64,4,False,True,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79039,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,4,15,56,20,stim_train,turban,1541,7,False,True,body_parts_and_apparel,2
80159,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,4,16,56,20,stim_train,iron,733,3,False,True,tools,5
81279,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,4,17,56,20,stim_train,cloud,320,0,False,True,unknown,0
82399,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,4,18,56,20,stim_train,sponge,1347,9,False,True,household_items_and_furniture,4
83519,/srv/eeg_reconstruction/shared/data/stimuli/re...,repr_eeg2,8,4,19,56,20,stim_train,biscuit,118,7,False,True,foods_and_plants,3

In [15]:
from brain_image.data import load_eeg_data


eeg, idxs, *_ = load_eeg_data(alljoined_path / "preprocessed_eeg" / "sub-08" / "preprocessed_eeg_training_flat.npy")
eeg.shape

torch.Size([66804, 32, 250])

In [ ]:
class ThingsEEG2Paths:
    def get_img_path(self, split, idx):
        return f""

    def get_eeg_path(self, split, idx)