In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path

In [4]:

from brain_image.data.alljoined_eeg2_dataset import AlljoinedEEG2Dataset, AlljoinedEEG2DatasetConfig


alljoined_path = Path("data/alljoined-1.6m")
c = AlljoinedEEG2DatasetConfig(subs=[1])
d = AlljoinedEEG2Dataset(c, split="train")
d

NotImplementedError:

In [5]:
d.metadata

NameError: name 'd' is not defined

In [ ]:
from typing import Literal
import numpy as np
from torch import Tensor
import torch



load_egg_values(alljoined_path / "preprocessed-eeg", [1], "train").shape

torch.Size([1, 66533, 32, 250])

In [19]:
eeg_obj["configs"]

{'baseline': (None, 0.0),
 'tmin': -0.2,
 'tmax': 1.0,
 'sfreq': 250,
 'l_freq': None,
 'h_freq': None,
 'notch_freqs': None,
 'mvnn_dim': 'epochs',
 'reject': None,
 'verbose': False}

In [18]:
from brain_image.data.alljoined_eeg2_dataset import load_metadatas


m = load_metadatas(alljoined_path / "preprocessed-eeg", alljoined_path / "stimuli/images", [1])
m

,image_path,subject,session,block_id,sequence_id,sequence_image_id,partition,category_name,category_num,category_img_num
0,data/alljoined-1.6m/stimuli/images/16641.jpg,1,1,1,1,1,test,jukebox,101,0
1,data/alljoined-1.6m/stimuli/images/16733.jpg,1,1,1,1,2,test,wallpaper,193,0
2,data/alljoined-1.6m/stimuli/images/16637.jpg,1,1,1,1,3,test,ice_cube,97,0
3,data/alljoined-1.6m/stimuli/images/16683.jpg,1,1,1,1,4,test,pug,143,0
4,data/alljoined-1.6m/stimuli/images/16558.jpg,1,1,1,1,5,test,bonnet,18,0
...,...,...,...,...,...,...,...,...,...,...
83512,data/alljoined-1.6m/stimuli/images/06603.jpg,1,4,19,56,13,train,harmonica,660,3
83513,data/alljoined-1.6m/stimuli/images/16176.jpg,1,4,19,56,14,train,whoopee_cushion,1617,6
83514,data/alljoined-1.6m/stimuli/images/04732.jpg,1,4,19,56,15,train,easel,473,2
83515,data/alljoined-1.6m/stimuli/images/08448.jpg,1,4,19,56,16,train,machine_gun,844,8
83516,data/alljoined-1.6m/stimuli/images/13032.jpg,1,4,19,56,17,train,sloth,1303,2

In [23]:
m.iloc[np.arange(5)]

,image_path,subject,session,block_id,sequence_id,sequence_image_id,partition,category_name,category_num,category_img_num
0,data/alljoined-1.6m/stimuli/images/16641.jpg,1,1,1,1,1,test,jukebox,101,0
1,data/alljoined-1.6m/stimuli/images/16733.jpg,1,1,1,1,2,test,wallpaper,193,0
2,data/alljoined-1.6m/stimuli/images/16637.jpg,1,1,1,1,3,test,ice_cube,97,0
3,data/alljoined-1.6m/stimuli/images/16683.jpg,1,1,1,1,4,test,pug,143,0
4,data/alljoined-1.6m/stimuli/images/16558.jpg,1,1,1,1,5,test,bonnet,18,0

In [14]:
m.query("partition=='train'")

,image_path,subject,session,block_id,sequence_id,sequence_image_id,partition,category_name,category_num,category_img_num
4080,data/alljoined-1.6m/stimuli/images/11134.jpg,1,1,5,1,1,train,puppy,1113,4
4082,data/alljoined-1.6m/stimuli/images/09852.jpg,1,1,5,1,3,train,paper_plate,985,2
4083,data/alljoined-1.6m/stimuli/images/15613.jpg,1,1,5,1,4,train,van,1561,3
4084,data/alljoined-1.6m/stimuli/images/01929.jpg,1,1,5,1,5,train,bulletproof_vest,192,9
4085,data/alljoined-1.6m/stimuli/images/00997.jpg,1,1,5,1,6,train,bee,99,7
...,...,...,...,...,...,...,...,...,...,...
83512,data/alljoined-1.6m/stimuli/images/06603.jpg,1,4,19,56,13,train,harmonica,660,3
83513,data/alljoined-1.6m/stimuli/images/16176.jpg,1,4,19,56,14,train,whoopee_cushion,1617,6
83514,data/alljoined-1.6m/stimuli/images/04732.jpg,1,4,19,56,15,train,easel,473,2
83515,data/alljoined-1.6m/stimuli/images/08448.jpg,1,4,19,56,16,train,machine_gun,844,8
83516,data/alljoined-1.6m/stimuli/images/13032.jpg,1,4,19,56,17,train,sloth,1303,2

In [8]:
eeg_obj["preprocessed_eeg_data"].shape

(66533, 32, 250)